name: workflow-testing
on:
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  test-job:
    runs-on: ubuntu-latest
    if: (github.event.pull_request && github.event.comment.body, '/ci')
    steps:
      - name: Echo a test message
        run: echo "Workflow triggered by comment!"
