name: workflow-testing
on:
  issue_comment:
    types: [created, edited]

jobs:
  test-job:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ci')    
    steps:
      - name: Echo a test message
        run: echo "Workflow triggered by comment!"
