name: workflow-testing
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - name: Previous steps
        run: echo "Previous steps here"
      - name: Await Approval
        # This step will pause until the environment approval is granted
      - name: Next steps
        run: echo "Next steps here"
