name: workflow-testing
on:
  workflow_dispatch:
jobs:
  initial-stage:
    runs-on: ubuntu-latest
    steps:
      - name: startup steps
        run: |
          echo "starting up!"
  approval-stage:
    runs-on: ubuntu-latest
    environment: 'staging'
    needs:
      - initial-stage
    steps:
      - run: echo "Approved to Prod"
  final-stage:
    runs-on: ubuntu-latest
    steps:
      - name: startup steps
        run: |
          echo "End!"
    needs:
      - approval-stage
