name: workflow-testing
on:
  issue_comment:
    types: [created, edited]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a test message
        run: echo "Workflow triggered by comment!"
